name: Test, Build, Pre-release
on: [push, pull_request]
jobs:
  test-build-publish:
    if: "!contains(github.event.head_commit.message, '[skip-ci]') && !contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npm run bootstrap
          npm run test
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
      - name: Generate prerelease
        if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'chore(deps-dev)')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git reset HEAD --hard
          npm run version:prerelease -- --preid=alpha --yes
          npm run publish -- --yes
